{
   "agent":{
      "metrics_collection_interval":60,
      "run_as_user":"cwagent"
   },
   "metrics":{
      "append_dimensions":{
         "InstanceId":"${aws:InstanceId}",
         "InstanceType":"${aws:InstanceType}"
      },
      "metrics_collected":{
         "mem":{
            "measurement":[
               "mem_used_percent"
            ],
            "metrics_collection_interval":60,
            "resources":[
               "*"
            ]
         },
         "disk":{
            "measurement":[
               "used_percent"
            ],
            "metrics_collection_interval":60,
            "resources":[
               "/",
               "/data",
               "/mnt/storage0",
               "/mnt/data",
               "/apidata",
               "/home",
               "/datasftp"
            ]
         }
      }
   }
}
